server:
  port: 10030
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: service-user #服务名
  datasource:
    url: jdbc:mysql:///learn-online-user?serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  main:
    allow-bean-definition-overriding: true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: lzc064212
    jedis:
      pool:
        max-wait: 2000ms
        min-idle: 2
        max-idle: 8

mybatis-plus:
  mapper-locations: classpath:com/richal/learnonline/mapper/*Mapper.xml


