server:
  port: 10050
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: service-common #服务名
  main:
    allow-bean-definition-overriding: true



